apply plugin: 'java'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'com.google.guava:guava:16.0.1'
    implementation 'com.google.code.findbugs:jsr305:2.0.1'
    implementation 'com.madgag.spongycastle:core:1.51.0.0'

    implementation 'com.lambdaworks:scrypt:1.4.0'

    implementation 'com.google.protobuf:protobuf-java:2.5.0'
    implementation 'org.slf4j:slf4j-jdk14:1.7.6'

//    implementation 'org.json:json:20140107'
    implementation 'org.json:json:20080701'

    implementation 'com.squareup.okhttp:okhttp:2.3.0'

    testImplementation 'junit:junit:4.11'
    testImplementation 'org.mockito:mockito-all:1.9.5'
    testImplementation 'com.squareup.okhttp:mockwebserver:2.3.0'
}
